#UR5:
#  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
#  kinematics_solver_search_resolution: 0.5
#  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
#  arm_prefix: gripper_ur5_
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
manipulator:
  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  arm_prefix: gripper_ur5_
UR5:
  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3