# see:
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater # The name of the plugin that we are using.
    point_cloud_topic: /gripper_camera/depth/points               # This specifies the topic to listen on for a point cloud.
    max_range: 5.0                                                # (in m) Points further than this will not be used.
    point_subsample: 1                                            # Choose one of every point_subsample points.
    padding_offset: 0.1                                           # The size of the padding (in cm).
    padding_scale: 1.0                                            #
    filtered_cloud_topic: /filtered_cloud                         # The topic on which the filtered cloud will be published (mainly for debugging). The filtering cloud is the resultant cloud after self-filtering has been performed.
#
#sensors:
#  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater # The name of the plugin that we are using.
#    image_topic: /gripper_camera/depth_registered/image_raw       # This specifies the topic to listen on for a depth image.
#    queue_size: 5                                                 # The number of images to queue up
#    near_clipping_plane_distance: 0.3                             #
#    far_clipping_plane_distance: 5.0                              #
#    shadow_threshold: 0.2                                         #
#    padding_scale: 4.0                                            #
#    padding_offset: 0.03                                          # The size of the padding (in cm).
#    filtered_cloud_topic: filtered_cloud                          # The topic on which the filtered cloud will be published (mainly for debugging). The filtering cloud is the resultant cloud after self-filtering has been performed.
