#goal definition
string mode
int32 position
int32 speed
int32 force
---
#result definition
robotiq_s_model_control/SModel_robot_input hand_status
string hand_info
---
#feedback
robotiq_s_model_control/SModel_robot_input hand_status