#goal definition
string mode
int32 position
int32 speed
int32 force
---
#result definition
robotiq_3f_gripper_articulated_msgs/Robotiq3FGripperRobotInput hand_status
string hand_info
---
#feedback
robotiq_3f_gripper_articulated_msgs/Robotiq3FGripperRobotInput hand_status