controller_list:
  - name: fake_stand_controller
    joints:
      []
  - name: fake_arm_controller
    joints:
      - gripper_ur5_shoulder_pan_joint
      - gripper_ur5_shoulder_lift_joint
      - gripper_ur5_elbow_joint
      - gripper_ur5_wrist_1_joint
      - gripper_ur5_wrist_2_joint
      - gripper_ur5_wrist_3_joint
  - name: fake_hand_controller
    joints:
      - gripper_robotiq_palm_finger_1_joint
      - gripper_robotiq_finger_1_joint_1
      - gripper_robotiq_finger_1_joint_2
      - gripper_robotiq_finger_1_joint_3
      - gripper_robotiq_palm_finger_2_joint
      - gripper_robotiq_finger_2_joint_1
      - gripper_robotiq_finger_2_joint_2
      - gripper_robotiq_finger_2_joint_3
      - gripper_robotiq_finger_middle_joint_1
      - gripper_robotiq_finger_middle_joint_2
      - gripper_robotiq_finger_middle_joint_3