planned_path_publisher: "move_group/display_planned_path"
group_name: "UR5"
planning_frame: "/base_link"
planning_time: 5
planning_attempts: 100
goal_tolerance: 0.01
goal_position_tolerance: 0.01
goal_orientation_tolerance: 0.01
goal_joint_tolerance: 0.01
planner: "SBLkConfigDefault"  # for parameter see the ompl_planning.yaml at julius_moveit
# SBLkConfigDefault
# ESTkConfigDefault
# LBKPIECEkConfigDefault
# BKPIECEkConfigDefault
# KPIECEkConfigDefault
# RRTkConfigDefault
# RRTConnectkConfigDefault
# RRTstarkConfigDefault
# TRRTkConfigDefault
# PRMkConfigDefault
# PRMstarkConfigDefault
ee_links:
  - gripper_robotiq_palm
  - gripper_robotiq_finger_1_link_0
  - gripper_robotiq_finger_1_link_1
  - gripper_robotiq_finger_1_link_2
  - gripper_robotiq_finger_1_link_3
  - gripper_robotiq_finger_2_link_0
  - gripper_robotiq_finger_2_link_1
  - gripper_robotiq_finger-2_link_2
  - gripper_robotiq_finger_2_link_3
  - gripper_robotiq_finger_middle_link_0
  - gripper_robotiq_finger_middle_link_1
  - gripper_robotiq_finger_middle_link_2
  - gripper_robotiq_finger_middle_link_3
allow_looking: False
allow_replanning: False