# Arm
arm:
  backup_joint_values: [-180, -90, 0.0, -90, 0.00, 0.0]
  home_joint_values:   [-2.00, -90, 0.0, -90, 0.00, 0.0]
  watch_joint_values:  [-180, -90, -90, -80, 90.0, 125]
  linear_tcp_speed: 0.10
  linear_tcp_acceleration: 0.04
  joint_speed: 15.0
  joint_acceleration: 4.0
  joint_states_topic: "/ur5/joint_states"