planned_path_publisher: "move_group/display_planned_path"
group_name: "UR5"
planning_frame: "/gripper_ur5_base_link"
planning_time: 10
planning_attempts: 100
goal_tolerance: 0.01
goal_position_tolerance: 0.1
goal_orientation_tolerance: 0.1
goal_joint_tolerance: 0.1
planner: "RRTConnectkConfigDefault"  # for parameter see the ompl_planning.yaml at julius_moveit
# SBLkConfigDefault             no
# ESTkConfigDefault
# LBKPIECEkConfigDefault
# BKPIECEkConfigDefault         no
# KPIECEkConfigDefault          no
# RRTkConfigDefault             no
# RRTConnectkConfigDefault      no
# RRTstarkConfigDefault         no
# TRRTkConfigDefault
# PRMkConfigDefault
# PRMstarkConfigDefault