haf_server_name: "/haf_server"
grasp_search_center: [0.6, 0.0 , -0.05]
gripper_approach_vector: [-1.0, 0.0, 0.0]
grasp_search_size_x: 50
grasp_search_size_y: 50
max_calculation_time: 10
show_only_best_grasp: true
base_frame_default: "gripper_camera_rgb_frame"
gripper_width: 1
input_pc_topic: "/gripper_camera/depth_registered/points"

grasp_quality_threshold: 50.0
grasp_search_timeout: 50.0