publisher_name: "/hand/Robotiq3FGripperRobotInput"
subscriber_name: "/hand/Robotiq3FGripperRobotInput "
hand_server_name: "/hand/gripper_action"
hand_mode: "basic"
toggle_depth_image_service_name: "/toggle_/gripper_d435/depth/image_rect_raw"