# parameter for the server and client alike
# grasp planing (haf)
haf_server_name: "/haf_server"
# arm
planned_path_publisher: "move_group/display_planned_path"
group_name: "UR5"
# controller
grasp_detection_frame: "gripper_camera_rgb_frame"