waypoints_station_1: # in degree [base, shoulder, elbow, wrist1, wrist2, wrist3]
  home_pose: [0, -90, 0, -90, 0, 0]
  watch_pose: [-180, -90, -90, -80, 90, 125]
  pre_grasp: [-171.5, -137.2, 120.3, -163.53, -80.8, 45.2]
  grasp: [-175.3, -114.9, 114.1, -179.5, -72.7, 45.3]
  post_grasp: [-174.1, -98.1, 50.8, -133.1, -79.1, 38.2]
  pre_set: [-186.9, -112.1, -79.9, 10.8, 96.4, 33.6]
  set: [-186.9, -198.8, -50, 67.6, 96.8, 33.8]
  post_set: [-190.6, -193.3, -86.9, 87.1, 100.3, 31.7]

waypoints_station_2: # in degree [base, shoulder, elbow, wrist1, wrist2, wrist3]
  home_pose: [0, -90, 0, -90, 0, 0]
  watch_pose: [-180, -90, -90, -80, 90, 125]
  pre_grasp: [-171.6, -134.6, 120.3, -167.5, -86.5, 38]
  grasp: [-176.2, -104, 104.4, -179.2, -87.7, 39.2]
  post_grasp: [-181.6, -88.7, 41.2, -135.9, -77.7, 40]
  pre_set: [-161.5, -112.1, -80, 10.8, 96.4, 33.6]
  set: [-158.8, -197.5, -58.6, 77.0, 94.0, 33.9]
  post_set: [-152.1, -192.5, -88.0, 88.5, 81.9, 40.2]

waypoints_station_3: # in degree [base, shoulder, elbow, wrist1, wrist2, wrist3]
  home_pose: [0, -90, 0, -90, 0, 0]
  watch_pose: [-180, -90, -90, -80, 90, 125]
  pre_grasp: [-177.3, -131.2, 117, -170.2, -100.2, 40.4]
  grasp: [-199.8, -108.3, 107.8, -177.2, -66.1, 40.6]
  post_grasp: [-199.8, -107.3, 96.7, -167.1, -66.2, 40.6]
  pre_set: [-219.1, -112.1, -80, 10.8, 96.4, 33.6]
  set: [-214.3, -194.4, -63.1, 74.8, 97.7, 40.6]
  post_set: [-222.2, -190.7, -80.3, 76.9, 104.5, 31.9]

backup_pos: [-180, -90, 0, -90, 0, 0]
linear_tcp_speed: 10
linear_tcp_acceleration: 5
joint_speed: 10
joint_acceleration: 5
joint_states_topic: "/ur5/joint_states"
# Hand/Gripper
publisher_name: "/hand/SModelRobotOutput"
subscriber_name: "/hand/SModelRobotInput"
hand_server_name: "/hand/gripper_action"
eef_link: "gripper_robotiq_palm_planning"
#Wlan Station - Pose Stamped - link: base_footprint
ssb_default_pose:
    position:
      x: 0.03
      y: 0.15
      z: 0.925
    orientation:
      x: 0
      y: 0
      z: 0.7071
      w: 0.7071
#Water Sample Station - Pose Stamped - link: water_sample_station_mount_link
wss_default_pose:
    position:
      x: 0.23
      y: -0.02
      z: 0.13
    orientation:
      x: 0
      y: 0
      z: 0.7071
      w: 0.7071
# Planning
# KPIECEkConfigDefault, RRTConnectkConfigDefault, RRTstarkConfigDefault, TRRTkConfigDefault
planner_id: "KPIECEkConfigDefault"
planner_time: 3.0
planner_attempts: 100
allow_replanning: True